extends LimboState

@export var action_data: Resource
@export var hitbox_path: NodePath = ^"AttackHitbox"

const HITBREAK_SOURCE_ACTOR_NAME_META := &"hitbreak_source_actor_name"
const HITBREAK_SOURCE_ACTOR_PATH_META := &"hitbreak_source_actor_path"
const HITBREAK_SOURCE_ATTACK_SEQUENCE_META := &"hitbreak_source_attack_sequence_id"
const HITBREAK_SOURCE_HITBOX_SEQUENCE_META := &"hitbreak_source_hitbox_sequence_id"

var _cooldown_until_sec: float = 0.0
var _attack_sequence_counter: int = 0
var _attack_sequence_id: int = 0
var _attack_phase: StringName = &"idle"
var _attack_started_runtime: bool = false
var _finished_normally: bool = false


func _enter() -> void:
	_reset_attack_telemetry()
	if agent == null:
		_finish_attack()
		return

	var now_sec: float = Time.get_ticks_msec() * 0.001
	if now_sec < _cooldown_until_sec:
		_finish_attack()
		return

	var stamina := agent.get_node_or_null(^"Stamina") as StaminaComponent
	if stamina != null:
		var resolved_action: Resource = _resolved_action_data()
		if resolved_action != null and resolved_action.get("stamina_cost") != null:
			var cost: float = float(resolved_action.get("stamina_cost"))
			if cost > 0.0:
				var required: float = float(agent.get_required_stamina_for_attack())
				if required <= 0.0:
					required = cost
				if not stamina.has_stamina(required):
					_finish_attack()
					return
				if not stamina.consume(cost):
					_finish_attack()
					return
				CombatTelemetry.emit_event(&"attack_stamina_cost", {
					"actor": str(agent.name),
					"attack_sequence_id": _attack_sequence_id,
					"amount": cost,
					"required": required
				})

	var telemetry_target: String = ""
	var has_valid_telemetry_target: bool = false
	var current_target: Node2D = agent.get_combat_target() as Node2D
	if is_instance_valid(current_target):
		telemetry_target = str(current_target.name)
		has_valid_telemetry_target = true
	if has_valid_telemetry_target:
		CombatTelemetry.emit_event(&"attack_started", {
			"actor": str(agent.name),
			"attack_sequence_id": _attack_sequence_id,
			"target": telemetry_target
		})
	_attack_started_runtime = true
	_emit_attack_phase(&"windup", telemetry_target)

	# Lock animation/state to attack execution; avoid walk visual while hit windows run.
	agent.stop_motor_movement()
	agent.play_attack_animation()
	agent.orient_attack_hitbox()

	var hitbox := agent.get_node_or_null(hitbox_path) as HitboxComponent
	if hitbox != null:
		_apply_action_to_hitbox(hitbox)
		hitbox.attack_sequence_id = _attack_sequence_id
		hitbox.set_hitbox_enabled(false, &"prepare")

	await get_tree().create_timer(_windup()).timeout
	if not is_active(): return
	_emit_attack_phase(&"active", telemetry_target)
	if hitbox != null:
		hitbox.attack_sequence_id = _attack_sequence_id
		hitbox.set_hitbox_enabled(true)

	await get_tree().create_timer(_active()).timeout
	if not is_active(): return
	if hitbox != null:
		hitbox.set_hitbox_enabled(false, &"active_elapsed")
	_emit_attack_phase(&"recover", telemetry_target)

	await get_tree().create_timer(_recover()).timeout
	if not is_active(): return
	await agent.wait_for_attack_animation_end(_windup() + _active() + _recover())
	if not is_active(): return
	_cooldown_until_sec = Time.get_ticks_msec() * 0.001 + _cooldown()
	_finish_attack()


func _exit() -> void:
	# Hardening: if this state is interrupted mid-coroutine, ensure combat does not stay locked.
	if agent != null:
		var hitbox := agent.get_node_or_null(hitbox_path) as HitboxComponent
		if hitbox != null:
			hitbox.set_hitbox_enabled(false, &"interrupted")
		if _attack_started_runtime and not _finished_normally:
			var interrupt_reason: StringName = _resolve_interrupt_reason()
			CombatTelemetry.emit_event(&"attack_interrupted", {
				"actor": str(agent.name),
				"attack_sequence_id": _attack_sequence_id,
				"phase": String(_attack_phase),
				"reason": String(interrupt_reason)
			})
			_emit_hitbreak_success_if_needed(interrupt_reason)
		agent.clear_attack_pending()


func _apply_action_to_hitbox(hitbox: Node) -> void:
	var resolved_action: Resource = _resolved_action_data()
	if resolved_action == null:
		return
	
	# The base_damage is retrieved directly from the resolved action data.
	# For the player, this is dynamically generated by the NexusEquipmentAdapter which ALREADY
	# includes the item's properties (rolled_damage).
	# However, our design requires applying the actor's DEX bonus to the final attack.
	var base_damage: float = float(resolved_action.get("damage"))
	
	# Since enemies use fallback action_data which hasn't been adapted dynamically yet,
	# their base_damage is the literal amount defined in their .tres file (e.g. 0.85 for Light, 1.25 for Brute).
	# If we add flat DEX * 0.5 here, an enemy with base_dex=10 will add 5.0 damage to a 0.85 attack!
	# Because we delegated base_dex to StatsComponent, all enemies now have a default base_dex of 0.0 unless configured.
	var dex: float = 0.0
	if agent != null and agent.has_method("get_stat_value"):
		dex = float(agent.call("get_stat_value", &"dex", 0.0))
		
	# Apply final damage.
	hitbox.damage = base_damage + (dex * 0.5)
	
	var action: CombatActionData = resolved_action as CombatActionData
	if action != null:
		if "knockback_force" in hitbox:
			hitbox.knockback_force = action.knockback_force
		if "knockback_duration_sec" in hitbox:
			hitbox.knockback_duration_sec = action.knockback_duration_sec
			
	hitbox.one_hit_per_target_per_attack = resolved_action.get("one_hit_per_target_per_attack")
	hitbox.max_targets_per_attack = resolved_action.get("max_targets_per_attack")


func _windup() -> float:
	var resolved_action: Resource = _resolved_action_data()
	return 0.12 if resolved_action == null else maxf(0.01, float(resolved_action.get("windup_sec")))


func _active() -> float:
	var resolved_action: Resource = _resolved_action_data()
	return 0.08 if resolved_action == null else maxf(0.01, float(resolved_action.get("active_sec")))


func _recover() -> float:
	var resolved_action: Resource = _resolved_action_data()
	return 0.16 if resolved_action == null else maxf(0.01, float(resolved_action.get("recover_sec")))


func _cooldown() -> float:
	var resolved_action: Resource = _resolved_action_data()
	return 0.24 if resolved_action == null else maxf(0.0, float(resolved_action.get("cooldown_sec")))


func _finish_attack() -> void:
	_finished_normally = true
	_attack_phase = &"finished"
	if agent != null:
		agent.clear_attack_pending()
	get_root().dispatch(EVENT_FINISHED)


func _resolved_action_data() -> Resource:
	if agent != null:
		var loadout: EquipmentLoadout = agent.get_equipment_loadout_runtime() as EquipmentLoadout
		if loadout != null and loadout.weapon != null and loadout.weapon.action_data != null:
			return loadout.weapon.action_data
	return action_data


func _reset_attack_telemetry() -> void:
	_attack_sequence_counter += 1
	_attack_sequence_id = _attack_sequence_counter
	_attack_phase = &"idle"
	_attack_started_runtime = false
	_finished_normally = false


func _emit_attack_phase(phase: StringName, target: String = "") -> void:
	_attack_phase = phase
	var payload := {
		"actor": str(agent.name),
		"attack_sequence_id": _attack_sequence_id,
		"phase": String(phase)
	}
	if not target.is_empty():
		payload["target"] = target
	CombatTelemetry.emit_event(&"attack_phase_started", payload)


func _resolve_interrupt_reason() -> StringName:
	if agent == null:
		return &"missing_agent"
	var health := agent.get_node_or_null(^"Health") as HealthComponent
	if health != null and not health.is_alive():
		if agent.has_meta(&"attack_interrupt_reason"):
			agent.remove_meta(&"attack_interrupt_reason")
		_clear_hitbreak_source_meta()
		return &"death"
	if agent.has_meta(&"attack_interrupt_reason"):
		var reason: StringName = StringName(str(agent.get_meta(&"attack_interrupt_reason")))
		agent.remove_meta(&"attack_interrupt_reason")
		return reason
	_clear_hitbreak_source_meta()
	return &"state_exit"


func _emit_hitbreak_success_if_needed(interrupt_reason: StringName) -> void:
	if agent == null:
		return
	if interrupt_reason != &"hit_reaction":
		_clear_hitbreak_source_meta()
		return
	if not agent.has_meta(HITBREAK_SOURCE_ACTOR_NAME_META):
		_clear_hitbreak_source_meta()
		return
	var source_actor_name: String = str(agent.get_meta(HITBREAK_SOURCE_ACTOR_NAME_META))
	var payload := {
		"actor": source_actor_name,
		"target": str(agent.name),
		"target_attack_sequence_id": _attack_sequence_id,
		"target_phase": String(_attack_phase),
		"reason": "hit_reaction"
	}
	if agent.has_meta(HITBREAK_SOURCE_ACTOR_PATH_META):
		payload["source_actor_path"] = str(agent.get_meta(HITBREAK_SOURCE_ACTOR_PATH_META))
	if agent.has_meta(HITBREAK_SOURCE_ATTACK_SEQUENCE_META):
		payload["source_attack_sequence_id"] = int(agent.get_meta(HITBREAK_SOURCE_ATTACK_SEQUENCE_META))
	if agent.has_meta(HITBREAK_SOURCE_HITBOX_SEQUENCE_META):
		payload["source_hitbox_sequence_id"] = int(agent.get_meta(HITBREAK_SOURCE_HITBOX_SEQUENCE_META))
	CombatTelemetry.emit_event(&"hitbreak_success", payload)
	_play_hitbreak_feedback(payload)
	_clear_hitbreak_source_meta()


func _play_hitbreak_feedback(payload: Dictionary) -> void:
	if not payload.has("source_actor_path"):
		return
	var source_actor := get_node_or_null(NodePath(str(payload.get("source_actor_path"))))
	if source_actor == null:
		return
	var feedback := source_actor.get_node_or_null(^"CombatFeedbackComponent")
	if feedback == null or not feedback.has_method("play_hitbreak_success"):
		return
	feedback.play_hitbreak_success(payload)


func _clear_hitbreak_source_meta() -> void:
	if agent == null:
		return
	if agent.has_meta(HITBREAK_SOURCE_ACTOR_NAME_META):
		agent.remove_meta(HITBREAK_SOURCE_ACTOR_NAME_META)
	if agent.has_meta(HITBREAK_SOURCE_ACTOR_PATH_META):
		agent.remove_meta(HITBREAK_SOURCE_ACTOR_PATH_META)
	if agent.has_meta(HITBREAK_SOURCE_ATTACK_SEQUENCE_META):
		agent.remove_meta(HITBREAK_SOURCE_ATTACK_SEQUENCE_META)
	if agent.has_meta(HITBREAK_SOURCE_HITBOX_SEQUENCE_META):
		agent.remove_meta(HITBREAK_SOURCE_HITBOX_SEQUENCE_META)
